FORMAT: 1A
HOST: http://sweague.me/api

# Sweague API

Sweague is a simple API allowing consumers to view information on Marvel Comics.
Our source can be found here: https://github.com/nickroberts404/cs373-idb

## Comics Collection [/comics]

### List All Comics [GET]

+ Response 200 (application/json)

    + Schema
        
            {
              "definitions": {
                "comic": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "id": {
                      "type": "number"
                    },
                    "issue_num": {
                      "type": "number"
                    },
                    "number_of_characters": {
                      "type": "number"
                    },
                    "number_of_creators": {
                      "type": "number"
                    },
                    "number_of_stories": {
                      "type": "number"
                    },
                    "page_count": {
                      "type": "number"
                    },
                    "thumbnail": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "description",
                    "id",
                    "issue_num",
                    "number_of_characters",
                    "number_of_creators",
                    "number_of_stories",
                    "page_count",
                    "thumbnail",
                    "title"
                  ]
                }
              },
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "comics": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/comic"
                  }
                },
                "count": {
                  "type": "number"
                }
              },
              "required": [
                "comics",
                "count"
              ]
            }
    
## Characters Collection [/characters]

### List All Characters [GET]

+ Response 200 (application/json)

    + Schema
        
            {
              "definitions": {
                "character": {
                  "type": "object",
                  "properties": {
                    "description": {
                      "type": "string"
                    },
                    "id": {
                      "type": "number"
                    },
                    "name": {
                      "type": "string"
                    },
                    "number_of_comics": {
                      "type": "number"
                    },
                    "number_of_series": {
                      "type": "number"
                    },
                    "number_of_stories": {
                      "type": "number"
                    },
                    "thumbnail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "description",
                    "id",
                    "name",
                    "number_of_comics",
                    "number_of_series",
                    "number_of_stories",
                    "thumbnail"
                  ]
                }
              },
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "characters": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/character"
                  }
                },
                "count": {
                    "type": "number"
                }
              },
              "required": [
                "characters",
                "count"
              ]
            }

## Creators Collection [/creators]

### List All Creators [GET]

+ Response 200 (application/json)

    + Schema
        
            {
              "definitions": {
                "creator": {
                  "type": "object",
                  "properties": {
                    "first_name": {
                      "type": "string"
                    },
                    "id": {
                      "type": "number"
                    },
                    "last_name": {
                      "type": "string"
                    },
                    "number_of_comics": {
                      "type": "number"
                    },
                    "number_of_series": {
                      "type": "number"
                    },
                    "number_of_stories": {
                      "type": "number"
                    },
                    "thumbnail": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "first_name",
                    "id",
                    "last_name",
                    "number_of_comics",
                    "number_of_series",
                    "number_of_stories",
                    "thumbnail"
                  ]
                }
              },
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "creators": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/creator"
                  }
                },
                "count": {
                  "type": "number"
                }
              },
              "required": [
                "creators",
                "count"
              ]
            }

## Query Comics [/comic/{comic_id}]

+ Parameters
    + comic_id (number) - Integer identifier of the comic


### Comic Details [GET]

+ Response 200 (application/json)

    + Schema
        
            {
              "definitions": {
                "creator": {
                  "type": "object",
                  "properties": {
                    "first_name": {
                      "type": "string"
                    },
                    "id": {
                      "type": "number"
                    },
                    "last_name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "first_name",
                    "id",
                    "last_name"
                  ]
                },
                "character": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number"
                    },
                    "name": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "name"
                  ]
                }
              },
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "comic": {
                  "type": "object",
                  "properties": {
                      "characters": {
                          "type": "array",
                          "items": {
                              "$ref": "#/definitions/character"
                          }
                      },
                      "creators": {
                          "type": "array",
                          "items": {
                              "$ref": "#/definitions/creator"
                          }
                      },
                      "description": {
                          "type": "string"
                      },
                      "id": {
                          "type": "number"
                      },
                      "issue_num": {
                          "type": "number"
                      },
                      "number_of_characters": {
                          "type": "number"
                      },
                      "number_of_creators": {
                          "type": "number"
                      },
                      "number_of_stories": {
                          "type": "number"
                      },
                      "page_count": {
                          "type": "number"
                      },
                      "thumbnail": {
                          "type": "string"
                      },
                      "title": {
                          "type": "string"
                      }
                  },
                  "required": [
                      "characters",
                      "creators",
                      "description",
                      "id",
                      "issue_num",
                      "number_of_characters",
                      "number_of_creators",
                      "number_of_stories",
                      "page_count",
                      "thumbnail",
                      "title"
                  ]
                }
              },
              "required": [
                "comic"
              ]
            }
        
## Query Characters [/character/{character_id}]

+ Parameters
    + character_id (number) - Integer identifier of the character

### Character Details [GET]

+ Response 200 (application/json)

    + Schema
    
            {
              "definitions": {
                "comic": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number"
                    },
                    "title": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "title"
                  ]
                }
              },
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "character": {
                  "type": "object",
                  "properties": {
                      "comics": {
                          "type": "array",
                          "items": {
                              "$ref": "#/definitions/comic"
                          }
                      },
                      "description": {
                          "type": "string"
                      },
                      "id": {
                          "type": "number"
                      },
                      "name": {
                          "type": "string"
                      },
                      "number_of_comics": {
                          "type": "number"
                      },
                      "number_of_series": {
                          "type": "number"
                      },
                      "number_of_stories": {
                          "type": "number"
                      },
                      "thumbnail": {
                          "type": "string"
                      }
                  },
                  "required": [
                      "comics",
                      "description",
                      "id",
                      "name",
                      "number_of_comics",
                      "number_of_series",
                      "number_of_stories",
                      "thumbnail"
                  ]
                }
              },
              "required": [
                "character"
              ]
            }
    
            
        
## Query Creators [/creator/{creator_id}]

+ Parameters
    + creator_id (number) - Integer identifier of the creator

### Creator Details [GET]

+ Response 200 (application/json)

    + Schema
    
            {
              "definitions": {
                "comic": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number"
                    },
                    "title": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "title"
                  ]
                }
              },
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "creator": {
                  "type": "object",
                  "properties": {
                      "comics": {
                          "type": "array",
                          "items": {
                              "$ref": "#/definitions/comic"
                          }
                      },
                      "first_name": {
                          "type": "string"
                      },
                      "id": {
                          "type": "number"
                      },
                      "last_name": {
                          "type": "string"
                      },
                      "number_of_comics": {
                          "type": "number"
                      },
                      "number_of_series": {
                          "type": "number"
                      },
                      "number_of_stories": {
                          "type": "number"
                      },
                      "thumbnail": {
                          "type": "string"
                      }
                  },
                  "required": [
                      "comics",
                      "first_name",
                      "id",
                      "last_name",
                      "number_of_comics",
                      "number_of_series",
                      "number_of_stories",
                      "thumbnail"
                  ]
                }
              },
              "required": [
                "creator"
              ]
            }
            
## Search [/search/{search_terms}]

+ Parameters

    + search_terms (string) - search terms delimited by spaces
    
### Search [GET]

+ Response 200 (application/json)
    
    + Schema
    
            {
                "definitions": {
                    "character": {
                        "type": "object",
                        "properties": {
                            "description": {
                                "type": "string"
                            },
                            "id": {
                                "type": "number"
                            },
                            "name": {
                                "type": "string"
                            },
                            "number_of_comics": {
                                "type": "number"
                            },
                            "number_of_series": {
                                "type": "number"
                            },
                            "number_of_stories": {
                                "type": "number"
                            },
                            "thumbnail": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "description",
                            "id",
                            "name",
                            "number_of_comics",
                            "number_of_series",
                            "number_of_stories",
                            "thumbnail"
                        ]
                    },
                    "comic": {
                        "type": "object",
                        "properties": {
                            "description": {
                                "type": "string"
                            },
                            "id": {
                                "type": "number"
                            },
                            "issue_num": {
                                "type": "number"
                            },
                            "number_of_characters": {
                                "type": "number"
                            },
                            "number_of_creators": {
                                "type": "number"
                            },
                            "number_of_stories": {
                                "type": "number"
                            },
                            "page_count": {
                                "type": "number"
                            },
                            "thumbnail": {
                                "type": "string"
                            },
                            "title": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "description",
                            "id",
                            "issue_num",
                            "number_of_characters",
                            "number_of_creators",
                            "number_of_stories",
                            "page_count",
                            "thumbnail",
                            "title"
                        ]
                    },
                    "creator": {
                        "type": "object",
                        "properties": {
                            "first_name": {
                                "type": "string"
                            },
                            "id": {
                                "type": "number"
                            },
                            "last_name": {
                                "type": "string"
                            },
                            "number_of_comics": {
                                "type": "number"
                            },
                            "number_of_series": {
                                "type": "number"
                            },
                            "number_of_stories": {
                                "type": "number"
                            },
                            "thumbnail": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "first_name",
                            "id",
                            "last_name",
                            "number_of_comics",
                            "number_of_series",
                            "number_of_stories",
                            "thumbnail"
                        ]
                    }
                },
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "characters_and": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/character"
                        }
                    },
                    "characters_or": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/character"
                        }
                    },
                    "comics_and": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/comic"
                        }
                    },
                    "comics_or": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/comic"
                        }
                    },
                    "creators_and": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/creator"
                        }
                    },
                    "creators_or": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/creator"
                        }
                    }
                },
                "required": [
                    "chracters_and",
                    "characters_or",
                    "comics_and",
                    "comics_or",
                    "creators_and",
                    "creators_or"
                ] 
            }